version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpass
      POSTGRES_DB: catdb
    ports:
      - "7080:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "7777:8080"